### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by Liqu1d82** [erickcion/tlwn722n-linux-install#2]
Hi, this morning I've installed your useful script to let my TL-WN722N getting recognized by Debian 8 in my notebook - I've installed kernel headers together with make / tar / wget but the script stops - here's the output:

Installing firware...

Changing to directory "compat-drivers-source"...
Trying to select the ath9k_htc diver to be compiled...
Processing new driver-select request...
Backing up makefile: Makefile.bk
Backup exists: Makefile.bk
Backup exists: Makefile.bk
Backup exists: Makefile.bk
Backup exists: Makefile.bk
Backing up makefile: drivers/net/wireless/Makefile.bk
Backing up makefile: drivers/net/wireless/ath/Makefile.bk
Backing up makefile: net/wireless/Makefile.bk
Backing up makefile: drivers/ssb/Makefile.bk
Backing up makefile: drivers/bcma/Makefile.bk
Backing up makefile: drivers/misc/eeprom/Makefile.bk
Backup exists: Makefile.bk
Compiling modules...
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
./scripts/gen-compat-autoconf.sh /home/randolph/tlwn722n-linux-install/compat-drivers-source/.config /home/randolph/tlwn722n-linux-install/compat-drivers-source/config.mk > include/linux/compat_autoconf.h
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
make -C /lib/modules/3.16.0-4-686-pae/build M=/home/randolph/tlwn722n-linux-install/compat-drivers-source modules
make[1]: ingresso nella directory "/usr/src/linux-headers-3.16.0-4-686-pae"
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
make[1]: Entering directory `/usr/src/linux-headers-3.16.0-4-686-pae'
Makefile:10: *** mixed implicit and normal rules: deprecated syntax
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/compat/main.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/compat/crc8.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/compat/compat_atomic.o
  LD [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/compat/compat.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/main.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/regd.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/hw.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/key.o
  LD [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/beacon.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/gpio.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/init.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/main.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/recv.o
/home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/recv.c:1019:11: warning: ‘fix_rssi_inv_only’ defined but not used [-Wunused-function]
 static s8 fix_rssi_inv_only(u8 rssi_val)
           ^
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/xmit.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/link.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/antenna.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/mci.o
/home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/mci.c: In function ‘ath_mci_cleanup’:
/home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/mci.c:478:22: warning: unused variable ‘buf’ [-Wunused-variable]
  struct ath_mci_buf *buf = &mci->sched_buf;
                      ^
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/rc.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/pci.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/wow.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/common.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/htc_hst.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/hif_usb.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/wmi.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/htc_drv_txrx.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/htc_drv_main.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/htc_drv_beacon.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/htc_drv_init.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/htc_drv_gpio.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9002_hw.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9003_hw.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/hw.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9003_phy.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9002_phy.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar5008_phy.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9002_calib.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9003_calib.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9003_rtt.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/calib.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/eeprom.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/eeprom_def.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/eeprom_4k.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/eeprom_9287.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ani.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/mac.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9002_mac.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9003_mac.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9003_eeprom.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9003_paprd.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/btcoex.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ar9003_mci.o
  LD [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ath9k.o
  LD [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ath9k_hw.o
  LD [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ath9k_common.o
  LD [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/drivers/net/wireless/ath/ath9k/ath9k_htc.o
  CC [M]  /home/randolph/tlwn722n-linux-install/compat-drivers-source/net/mac80211/main.o
/home/randolph/tlwn722n-linux-install/compat-drivers-source/net/mac80211/main.c: In function ‘ieee80211_alloc_hw’:
/home/randolph/tlwn722n-linux-install/compat-drivers-source/net/mac80211/main.c:633:2: error: implicit declaration of function ‘idr_pre_get’ [-Werror=implicit-function-declaration]
  idr_pre_get(&local->ack_status_frames, GFP_KERNEL);
  ^
cc1: some warnings being treated as errors
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:262: set di istruzioni per l'obiettivo "/home/randolph/tlwn722n-linux-install/compat-drivers-source/net/mac80211/main.o" non riuscito
make[5]: *** [/home/randolph/tlwn722n-linux-install/compat-drivers-source/net/mac80211/main.o] Errore 1
/usr/src/linux-headers-3.16.0-4-common/scripts/Makefile.build:409: set di istruzioni per l'obiettivo "/home/randolph/tlwn722n-linux-install/compat-drivers-source/net/mac80211" non riuscito
make[4]: *** [/home/randolph/tlwn722n-linux-install/compat-drivers-source/net/mac80211] Errore 2
/usr/src/linux-headers-3.16.0-4-common/Makefile:1352: set di istruzioni per l'obiettivo "_module_/home/randolph/tlwn722n-linux-install/compat-drivers-source" non riuscito
make[3]: *** [_module_/home/randolph/tlwn722n-linux-install/compat-drivers-source] Errore 2
Makefile:181: set di istruzioni per l'obiettivo "sub-make" non riuscito
make[2]: *** [sub-make] Errore 2
Makefile:8: set di istruzioni per l'obiettivo "all" non riuscito
make[1]: *** [all] Errore 2
make[1]: uscita dalla directory "/usr/src/linux-headers-3.16.0-4-686-pae"
Makefile:90: set di istruzioni per l'obiettivo "modules" non riuscito
make: *** [modules] Errore 2
There was a problem compiling the package.

Can you help me resolving this problem? Thanks.

**Comment by Liqu1d82** [comment]
Sorry for the request, I've resolved with a simple sudo apt-get install firmware-atheros.

**Comment by erickcion** [comment]
That's OK Randolph,

Your kernel version does not require this script. It is for kernel versions
lower than 3.x.
On Jun 26, 2016 6:24 AM, "Randolph Carter" <notifications@github.com> wrote:

Closed #2 <https://github.com/erickcion/tlwn722n-linux-install/issues/2>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/erickcion/tlwn722n-linux-install/issues/2#event-704211943>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAbCOpcN_U52MGVz7bTzkp_0uUook3PIks5qPlNzgaJpZM4I-hsk>
.
